/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type NewsletterIssue = {
  _id: string;
  _type: "newsletterIssue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  site: "churchMain" | "womanExcel";
  title: string;
  slug: Slug;
  publishedAt: string;
  issue?: number;
  excerpt: string;
  coverImage?: EditorialImage;
  body: PortableText;
  relatedLink?: Link;
  seo?: Seo;
  migrationMetadata?: MigrationMetadata;
};

export type MigrationMetadata = {
  _type: "migrationMetadata";
  sourceKey: string;
  sourcePath: string;
  sourceHash: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
};

export type Link = {
  _type: "link";
  label?: string;
  href: string;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        {
          _key: string;
        } & Link
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & EditorialImage)
>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type EditorialImage = {
  _type: "editorialImage";
  asset: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  decorative?: boolean;
  alt?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | NewsletterIssue
  | MigrationMetadata
  | Seo
  | Link
  | PortableText
  | SanityImageAssetReference
  | EditorialImage
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../churchmain/src/data/newsletters.ts
// Variable: CHURCH_MAIN_NEWSLETTERS_QUERY
// Query: *[    _type == "newsletterIssue" &&    site == "churchMain" &&    defined(slug.current) &&    defined(publishedAt)  ] | order(publishedAt desc, _id) {    _id,    title,    "slug": slug.current,    publishedAt,    issue,    excerpt,    coverImage {      alt,      decorative,      "url": asset->url,      "dimensions": asset->metadata.dimensions    },    relatedLink {      label,      href    },    seo {      title,      description    },    body[] {      ...,      _type == "editorialImage" => {        alt,        decorative,        "url": asset->url,        "dimensions": asset->metadata.dimensions      }    }  }
export type CHURCH_MAIN_NEWSLETTERS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  publishedAt: string;
  issue: number | null;
  excerpt: string;
  coverImage: {
    alt: string | null;
    decorative: boolean | null;
    url: string;
    dimensions: SanityImageDimensions | null;
  } | null;
  relatedLink: {
    label: string | null;
    href: string;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          {
            _key: string;
          } & Link
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "editorialImage";
        asset: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        decorative: boolean | null;
        alt: string | null;
        url: string;
        dimensions: SanityImageDimensions | null;
      }
  >;
}>;

// Source: ../womanexcel/src/lib/newsletters.ts
// Variable: WOMAN_EXCEL_NEWSLETTERS_QUERY
// Query: *[_type == "newsletterIssue" && site == "womanExcel" && defined(slug.current) && defined(publishedAt)]    | order(publishedAt desc, slug.current asc) {      _id,      title,      "slug": slug.current,      publishedAt,      issue,      excerpt,      coverImage {        alt,        decorative,        "url": asset->url,        "dimensions": asset->metadata.dimensions      },      relatedLink { label, href },      seo { title, description },      body[] {        ...,        _type == "editorialImage" => {          alt,          decorative,          "url": asset->url,          "dimensions": asset->metadata.dimensions        }      }    }
export type WOMAN_EXCEL_NEWSLETTERS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  publishedAt: string;
  issue: number | null;
  excerpt: string;
  coverImage: {
    alt: string | null;
    decorative: boolean | null;
    url: string;
    dimensions: SanityImageDimensions | null;
  } | null;
  relatedLink: {
    label: string | null;
    href: string;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          {
            _key: string;
          } & Link
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "editorialImage";
        asset: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        decorative: boolean | null;
        alt: string | null;
        url: string;
        dimensions: SanityImageDimensions | null;
      }
  >;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n    _type == "newsletterIssue" &&\n    site == "churchMain" &&\n    defined(slug.current) &&\n    defined(publishedAt)\n  ] | order(publishedAt desc, _id) {\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    issue,\n    excerpt,\n    coverImage {\n      alt,\n      decorative,\n      "url": asset->url,\n      "dimensions": asset->metadata.dimensions\n    },\n    relatedLink {\n      label,\n      href\n    },\n    seo {\n      title,\n      description\n    },\n    body[] {\n      ...,\n      _type == "editorialImage" => {\n        alt,\n        decorative,\n        "url": asset->url,\n        "dimensions": asset->metadata.dimensions\n      }\n    }\n  }\n': CHURCH_MAIN_NEWSLETTERS_QUERY_RESULT;
    '\n  *[_type == "newsletterIssue" && site == "womanExcel" && defined(slug.current) && defined(publishedAt)]\n    | order(publishedAt desc, slug.current asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      publishedAt,\n      issue,\n      excerpt,\n      coverImage {\n        alt,\n        decorative,\n        "url": asset->url,\n        "dimensions": asset->metadata.dimensions\n      },\n      relatedLink { label, href },\n      seo { title, description },\n      body[] {\n        ...,\n        _type == "editorialImage" => {\n          alt,\n          decorative,\n          "url": asset->url,\n          "dimensions": asset->metadata.dimensions\n        }\n      }\n    }\n': WOMAN_EXCEL_NEWSLETTERS_QUERY_RESULT;
  }
}
